import React, {Component} from 'react';

class Dracena extends Component   {

        render () {
            return (
                <div className='f4 tl'>
                    <h2 id="dracena" className='f2 tc'>Dracena</h2>
                        <p>Omawiana roślina jest sukulentem, którego naturalnym środowiskiem występowania jest Afryka, Azja, Australia oraz Meksyk. Co ciekawe, gatunki draceny mogą się od siebie różnić wielkością, ubarwieniem oraz kształtem liści. Większość tych gatunków bardzo dobrze nadaje się do uprawy doniczkowej. Roślina ta ozdobi każde wnętrze, a dodatkowo nie wymaga specjalnych zabiegów pielęgnacyjnych wymagających wiedzy specjalistycznej. Dracena jest zdecydowanie rośliną, z której pielęgnacją poradzą sobie osoby mające trudności w opiece nad kwiatami. Dracena jest wytrzymała na wiele pomyłek, chociażby takich, jak zapominanie podlewania. Roślina magazynuje wodę w swoim pniu. Hodowanie jej niesie za sobą nie tylko aspekt estetyczny i wizualny, ale zgodnie z wynikami przeprowadzonych badań, poprawia jakość powietrza w swoim otoczeniu. Dracena neutralizuje zanieczyszczenia, absorbuje szkodliwe związki, między innymi formaldehydy.</p>
                        <p>Królową dracen uprawianych w doniczkach jest dracena obrzeżona, nazywana też draceną marginatą. Pochodzi ona z Madagaskaru. Cechą charakterystyczną jest pióropusz cienkich liści o ostrych końcówkach, które wieńczą pień / łodygę. W zależności od odmiany mogą one przybierać różne kolory. Nierzadkim przypadkiem jest to, że liście są wielobarwne. Roślina w swoim naturalnym środowisku potrafi osiągnąć wysokość trzech metrów. W hodowli doniczkowej osiągają wysokość nie większą niż 2 metry. Popularność w naszych domach zyskała także dracena wonna, zwana też draceną fragrans lub smokowcem wonnym. Tą odmianę w naturze możemy spotkać w Afryce. W odróżnieniu od wcześniej opisywanej odmiany ma grubszy pień oraz szersze, lancetowate liście. Wyrastają one z pędu tworząc coś na kształt parasola. Liście mogą osiągnąć długość nawet metra. Kwiatostan w kolorze zielonkawo-białym zebrany w wiechę wydziela intensywny zapach. </p>
                        <p>Interesująco wygląda dracena Sandera. Ta odmiana zwana też jest ze względu na swoje podobieństwo „szczęśliwym bambusem”. Pochodzi ona z Azji i swoim wyglądem potrafi zmylić przez co często brana jest za bambusa. Roślina ta jest niezwykle łatwa w uprawie, gdyż może rosnąć w samej wodzie.  Warto również zwrócić uwagę na dracenę surculosa (rozgałęziona), która charakteryzuje się  owalnymi liśćmi z kolorowymi plamkami. </p>
                        <h3>Pielęgnacja i uprawa draceny w warunkach domowych – problemy z tym związane</h3>
                        <p>Roślina nie wymaga specjalnego traktowania. Jej uprawa jest dziecinnie prosta i powinien poradzić sobie z nią każdy. Spełnienie podstawowych warunków draceny może zaowocować, kwitnieniem rośliny. Warto pamiętać o kilku podstawowych zasadach. Po pierwsze dracena kocha ciepło. Należy pilnować, by temperatura w pomieszczeniu, w którym ją trzymamy nie spadała poniżej 15 stopni Celsjusza. Kolejnym ważnym aspektem jest to, że roślina uwielbia duże nasłonecznienie. Nic dziwnego, dracena ma pochodzenie z ciepłych krajów, gdzie jest dużo światła. Największe naświetlenie wymagają odmiany z barwnymi liśćmi. Jest to dla nich o tyle ważne, że potrafią stracić swój kolor, jeżeli pozostawimy roślinę w cieniu. Część gatunków będzie świetnie czuło się na parapecie od południowej strony. Nasłonecznienie nie może być zbyt ostre, bo możemy poparzyć liście. Najlepiej dracenę hodować w nasłonecznionym miejscu z rozproszonym światłem. </p>
                        <p>Dracena jest dobrą rośliną do uprawy w domu, gdyż dobrze znosi trudne warunki, takie jak suche powietrze. Warto jednak spryskiwać jej liście wodą, wtedy roślina ucieszy nasze oko ich barwą. Zabieg ten zalecamy wykonywać w zimie. Podczas sezonu grzewczego wilgotność powietrza spada i może osiągnąć zbyt niski poziom dla uprawy draceny. Szczególną uwagę musimy zwracać, jeżeli posiadamy odmianę o kolorowych liściach, gdyż wymagają one więcej wilgoci. Zalecamy również wycierać liście rośliny z kurzu przy pomocy wilgotnej ściereczki. </p>
                        <p>Dracena nie wymaga dużego nawodnienia. Podlewamy ją zatem oszczędnie, zwłaszcza na jesieni i w zimie. Wtedy ta roślina odpoczywa. W pozostałych okresach roku należy zwiększyć intensywność podlewania, lecz z umiarem. Zalecamy zachowanie zasady: podlewam, gdy w doniczce jest sucho. Dracena nie lubi nadmiernej wilgoci, a pozostawienie jej w wodzie powoduje, że roślina niszczeje. Zaczynają wtedy gnić korzenie. Przesuszenie rośliny powoduje opadanie liści. </p>
                        <h3>Nawożenie i przesadzanie Draceny</h3>
                        <p>Roślina uwielbia żyzne, próchnicze, nieprzepuszczające podłoże. Miesiące ciepłe (marzec – sierpień) to okres wzrostu draceny. Warto wtedy wspomagać roślinę roztworem nawozu wieloskładnikowego, stosując go co 2 tygodnie. Odporność draceny sprawia, że nawet jak zrobimy to rzadziej to nic się nie stanie. W pozostałych miesiącach nie nawozimy rośliny. </p>
                        <p>Młode rośliny charakteryzują się szybkim wzrostem. Dlatego zaleca się coroczne przesadzanie draceny na początku jej życia. Rośliny w podeszłym wieku przesadzamy co dwa, trzy lata. Pamiętajmy, że każda kolejna doniczka powinna być jedynie niewiele większa od poprzedniej. Na jej dno warto wsypać kermazyt ogrodniczy lub drobne kamyczki. Zapewni to naszemu okazowi właściwy drenaż. Roślinę można umieścić w ziemi uniwersalnej dla roślin doniczkowych lub w specjalistycznej dedykowanej palmom. </p>
                        <p>Do rozmnożenia draceny wykorzystujemy sadzonki wierzchołkowe. Pobieramy je wiosną. Następnie warto spryskać je preparatem grzybobójczym i umieścić w torfie. Temperatura otoczenia miejsca gdzie przechowujemy sadzonki powinna wynosić około 25 stopni Celsjusza. Na koniec umieszczamy sadzonki w przepuszczalnym podłożu. Inną metodą rozrodu draceny jest wykorzystanie pędów, ale trwa to znacznie dłużej. </p>
                        <h3>Choroby draceny</h3>
                        <p>Najczęstszy problemem w hodowli draceny są suche końcówki liści. Są one efektem zbyt suchego powietrza. Zaleca się pryskanie liści w okresie wzrostu rośliny. Jeżeli dracena gubi dolne liście, oznacza to złą temperaturę otoczenia. Dotyczy to zarówno przypadku zbyt niskiej, jak i zbyt wysokiej temperatury. Nadmiernie duży wzrost temperatury może powodować pęknięcia liści. Pojawiają się przy nasadach powierzchni blaszkowych. Większość problemów z draceną wynika ze złych warunków hodowli. Należy dbać o odpowiednią wilgotność, temperaturę oraz nasłonecznienie. Dracena może zapaść również na choroby o podłożu bakteryjnym. Bardzo często pojawiają się wtedy plamy na liściach. Do zwalczania tego typu chorób służą specjalne preparaty. </p>
                        <hr></hr>
                    </div>
            );
        }
    }
    
    export default Dracena;

