import React, {Component} from 'react';

class Morgana extends Component   {
    
        render () {
            return (
                <div className='f4 tl'>
                    <h2 id="morgana" className='f2 tc'>Rozchodnik Morgana</h2>
                    <h3>Uprawa i rozmnażanie</h3>
                    <p>Rozchodnik Morgana (Sedum morganianum) to sukulent o mięsistych zwisających pędach i wałeczkowatych liściach. Jest to roślina doniczkowa łatwa w uprawie, idealna do jasnych, słonecznych i ciepłych pomieszczeń. W tym artykule wyjaśniamy jakie zastosowanie może mieć Rozchodnik Morgana i jakie są właściwości tej rośliny. Zobacz jak wygląda uprawa rozchodnika w domu, a także jakie są najlepsze sposoby na jego rozmnażanie. </p>
                    <h3>Opis wyglądu</h3>	
                    <p>Rozchodnik Morgana należy do rodziny gruboszowatych (Crassulaceae) i jest powszechnie hodowany w domach od końca lat trzydziestych XX wieku. Szybko stał się jednym z najbardziej lubianych sukulentów. Podobnie jak inni przedstawiciele rodzaju rozchodnik (Sedum), Rozchodnik Morgana może przetrwać prawie 6 miesięcy bez wody, o ile wcześniej zgromadzi jej zapasy w mięsistych pędach i liściach. Ze względu na brak mrozoodporności ten gatunek rozchodnika nie nadaje się do uprawy ogrodowej w naszym klimacie ale na lato doniczki z roślinami można wystawiać na zewnątrz. </p>
                    <h3>Uprawa i rozmnażanie</h3>	
                    <p>Rozchodnik Morgana (Sedum morganianum) to sukulent o mięsistych zwisających pędach i wałeczkowatych liściach. Jest to roślina doniczkowa łatwa w uprawie, idealna do jasnych, słonecznych i ciepłych pomieszczeń. W tym artykule wyjaśniamy jakie zastosowanie może mieć Rozchodnik Morgana i jakie są właściwości tej rośliny. Zobacz jak wygląda uprawa rozchodnika w domu, a także jakie są najlepsze sposoby na jego rozmnażanie. </p>
                    <h3>Opis wyglądu</h3>	
                    <p>Rozchodnik Morgana należy do rodziny gruboszowatych (Crassulaceae) i jest powszechnie hodowany w domach od końca lat trzydziestych XX wieku. Szybko stał się jednym z najbardziej lubianych sukulentów. Podobnie jak inni przedstawiciele rodzaju rozchodnik (Sedum), Rozchodnik Morgana może przetrwać prawie 6 miesięcy bez wody, o ile wcześniej zgromadzi jej zapasy w mięsistych pędach i liściach. Ze względu na brak mrozoodporności ten gatunek rozchodnika nie nadaje się do uprawy ogrodowej w naszym klimacie ale na lato doniczki z roślinami można wystawiać na zewnątrz. </p>
                    <p>Mimo, że Rozchodnik Morgana był powszechnie dostępny w sprzedaży, przez długi czas miejsce pochodzenia tego gatunku było nieznane. Po latach poszukiwań, dopiero w 2008 r. meksykańscy botanicy znaleźli naturalne miejsce występowania tego gatunku i ustalili, że Rozchodnik Morgana pochodzi z południowych regionów Meksyku. Najczęściej porasta skarpy i skały, wrastając między trudno dostępne szczeliny. </p>
                    <p>Mięsiste, zwisające pędy rozchodnika morgana mają 60-100 cm długości i są gęsto porośnięte przez cylindryczne liście. Liście rosną na łodydze koliście i są ułożone blisko siebie, przez co pędy sprawiają wrażenie łuskowatych ogonów zwisających z doniczki. Zarówno łodygi, jak i liście rozchodnika morgana pokryte są woskowym nalotem, który zapobiega utracie wody. </p>
                    <p>Latem i jesienią na końcach pędów pojawiają się drobne, gwiazdkowate, różowe, czerwone lub czerwono-purpurowe kwiaty rozchodnika morgana. Jednak ten gatunek rzadko kwitnie w mieszkaniach. Żeby rozchodnik zakwitł musimy poczekać aż dojrzeje, a pędy będą miały przynajmniej 25 cm długości. Przeniesienie rośliny latem na zewnątrz i utrzymywanie jej zimą w temperaturach niższych niż pokojowa może pobudzić rozchodnik do kwitnienia. </p>
                    <p>Ze względu na płożący pokrój Rozchodnik Morgana najlepiej uprawiać w taki sposób, żeby ozdobne pędy mogły zwisać swobodnie w dół. Wiszące kosze, skrzynki balkonowe lub donice na postumentach wyeksponują urodę tej rośliny. </p>
                    <h3>Warto wiedzieć! </h3>
                    <p>Podczas podlewania i pielęgnacji starajmy się nie dotykać rozchodnika morgana. Pokrywający pędy i liście srebrzysty kutner łatwo ściera się pod wpływem dotyku i roślina traci na dekoracyjności. </p>
                    <h3><strong>Rozchodnik Morgana - czy jest trujący</strong></h3>
                    <p>Rozchodnik Morgana, podobnie jak inne gatunki rozchodników, ma szereg właściwości leczniczych. Już od dawna w medycynie ludowej wyciągi, nalewki czy okłady z rozchodnika miały wiele zastosowań, zarówno zewnętrznie (leczenie chorób skór i opuchlizn), jak i wewnętrznie (dolegliwości układu pokarmowego oraz infekcje górnych dróg oddechowych). Jednak ze względu na zawartość silnie działających alkaloidów, spożycie większego fragmentu tej rośliny może spowodować dolegliwości ze strony układu pokarmowego oraz naczyniowo-sercowego. Leki na bazie rozchodnika należy stosować wyłącznie po konsultacji z lekarzem. </p>
                    <p>Podsumowując - Rozchodnik Morgana <strong>nie jest to trująca roślina </strong>doniczkowa i możemy bezpiecznie uprawiać ją w domu, o ile mamy pewność, że przypadkowo jej fragmentów nie zje zaciekawione dziecko lub zwierzę domowe. </p>
                    <h3> Wymagania i uprawa</h3>	
                    <p>Rozchodnik Morgana ma wysokie wymagania termiczne, w związku z czym w naszym klimacie może być hodowany wyłącznie w mieszkaniach czy szklarniach. Najlepiej Rozchodnik Morgana czuje się w temperaturze 18-24°C. W naszych domach przechodzi zimą w stan spoczynku. W tym czasie ograniczamy podlewanie, zaprzestajemy nawożenia i obniżamy temperaturę powietrza do około 10°C. Jeżeli nie możemy obniżyć temperatury na zimę, warto dla równowagi zdecydować się na doświetlanie roślin w okresie od listopada do lutego wykorzystując odpowiednie lampy LED do roślin. </p>
                    <p>Rozchodnik Morgana wymaga dużej ilości światła słonecznego, dlatego doniczkę należy ustawić tak, aby słońce padało na roślinę przez co najmniej 4 godziny dziennie. Pamiętajmy, że bezpośrednie słońce nie służy rozchodnikowi, a idealne jest światło przefiltrowane (np. przez firankę). Latem, pod wpływem zbyt intensywnego światła słonecznego Rozchodnik Morgana może ulec uszkodzeniu. W najlepszym przypadku liście zmienią kolor z niebieskozielonego na pomarańczowożółty. Mimo, że z biegiem czasu wybarwienie powróci do normy, latem poparzona roślina będzie bardzo osłabiona. Rozchodnik nie lubi także nagłych zmian temperatur i przeciągów.</p>
                    <h3>Sadzenie</h3>	
                    <p>Rozchodnik Morgana ma słabo rozwinięty system korzeniowy, więc wystarczy mu niewielka doniczka. Na dnie umieszczamy warstwę żwirku lub keramzytu. Następnie wypełniamy pojemnik ziemią do kaktusów lub uniwersalnym podłożem do kwiatów, wymieszanym z piaskiem w stosunku 1:1. Ważne, żeby podłoże było luźne i przepuszczalne. </p>
                    <h3> Podlewanie</h3>	
                    <p>Jak każdy sukulent, Rozchodnik Morgana świetnie sobie radzi z suszą. Powinien być podlewany obficie, ale niezbyt często. Latem co 10-14 dni, a w miesiącach chłodniejszych jeszcze rzadziej (raz na 3-4 tygodnie). Generalnie podlewamy roślinę, gdy zauważymy, że liście zaczynają się marszczyć, a ziemia pomiędzy kolejnymi podlewaniami całkowicie wyschnie. Nadmierne podlewanie rozchodnika morgana jest o wiele bardziej niebezpieczne niż przesuszenie. Jeśli woda zalega w podłożu, korzenie i szyjka korzeniowa rozchodnika szybko zaczynają gnić. </p>
                    <h3>Nawożenie</h3>
                    <p>Podlewanie rozchodnika możemy połączyć z nawożeniem. Roślina nie ma dużych wymagań nawozowych. Dokarmiamy ją od marca do września stosując raz w miesiącu nawóz do kaktusów. Stosujemy jedynie połowę dawki zalecanej przez producenta nawozu. W okresie zimowego spoczynku całkowicie zaprzestajemy nawożenia. </p>
                    <h3>Przycinanie</h3>
                    <p>Rozchodnik Morgana nie wymaga przycinania, natomiast czasem konieczne jest usunięcie bezlistnych czy uschniętych pędów. W przeciwnym razie roślina straci swój atrakcyjny wygląd. </p>
                    <h3> Rozmnażanie</h3>
                    <p>Rozchodnik Morgana można rozmnożyć łatwo i na wiele sposobów: przez sadzonki liściowe, pędowe, a także przez podział. Chociaż roślinę można rozmnażać przez cały rok, najlepszym terminem rozmnażanie rozchodnika jest wiosna, gdy nasz okaz rozpoczyna aktywny wzrost. </p>
                    <p>Najpopularniejszą metodą rozmnażania rozchodnika morgana jest pozyskiwanie nowych roślin z liści i fragmentów pędów. Fragmenty pędów wciskamy delikatnie w podłoże do sadzonkowania, a następnie lekko podlewamy. Pojemnik z sadzonkami umieszczamy w ocienionym miejscu o temperaturze ok. 18°C. Po 2-3 tygodniach sadzonki powinny się ukorzenić. </p>
                    <p>Równie łatwo możemy rozmnożyć Rozchodnik Morgana pobierając fragment pędu, z którego przygotowujemy 5-7 cm sadzonki. Dolną część sadzonki oczyszczamy z liści, po czym pozostawiamy w suchym miejscu na 1-3 doby, żeby nieco przeschła. Następnie umieszczamy sadzonkę w pojemniku wypełnionym podłożem do sadzonkowania i podlewamy. Powinna się szybko się ukorzenić w ciągu kilku tygodni. </p>
                    <p>Jeśli dysponujemy dojrzałym, wyrośniętym egzemplarzem rozchodnika, możemy delikatnie wyjąć roślinę z ziemi i podzielić na kilka części, tak by każda miała silne i zdrowe korzenie. Sadzonki rozchodnika otrzymane z podziału rośliny od razu umieszczamy w doniczkach z podłożem dla kaktusów i sukulentów. </p>
                 <hr></hr>
                </div>
            );
        }
    }
    
    export default Morgana;